postgres:
  database: test_${LOC8_DB_DATABASE}
  user: ${LOC8_DB_USER}
  password: ${LOC8_DB_PASSWORD}
  host: ${LOC8_DB_HOST}
  port: ${LOC8_DB_PORT}
  minsize: ${LOC8_DB_MINSIZE}
  maxsize: ${LOC8_DB_MAXSIZE}

host: ${LOC8_HOST}
port: ${LOC8_PORT}
jwt_secret: ${LOC8_JWT_SECRET}
