version: "3.8"
services:
  timescaledb:
    image: timescale/timescaledb:1.7.4-pg12
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5438:5432"
    volumes:
      - timescaledbbase0:/var/lib/postgresql
      - timescaledblogs0:/var/log
volumes:
  timescaledblogs0: {}
  timescaledbbase0: {}
