"""change detection model

Revision ID: 0387fb37182e
Revises: 
Create Date: 2020-12-01 23:10:31.049412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import sessionmaker

Session = sessionmaker()

# revision identifiers, used by Alembic.
revision = '0387fb37182e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('hubId', sa.String(length=80), nullable=False),
    sa.Column('objectId', sa.String(length=80), nullable=False),
    sa.Column('distance', sa.Numeric(), nullable=False),
    sa.Column('major', sa.Numeric(), nullable=False),
    sa.Column('minor', sa.Numeric(), nullable=False),
    sa.Column('rssi', sa.Numeric(), nullable=False),
    sa.Column('rxpower', sa.Numeric(), nullable=False)
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceId', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('firmware', sa.String(length=100), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('env', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hubId', sa.String(length=80), nullable=False),
    sa.Column('deviceId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['deviceId'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objectId', sa.String(length=80), nullable=False),
    sa.Column('deviceId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['deviceId'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    bind = op.get_bind()
    session = Session(bind=bind)
    q = """
    SELECT create_hypertable('detections', 'ts');
    """
    session.execute(q)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objects')
    op.drop_table('hubs')
    op.drop_table('devices')
    op.drop_table('detections')
    # ### end Alembic commands ###
